/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OteviraciDobaRouteImport } from './routes/oteviraci-doba'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FotogalerieRouteImport } from './routes/fotogalerie'
import { Route as IndexRouteImport } from './routes/index'

const OteviraciDobaRoute = OteviraciDobaRouteImport.update({
  id: '/oteviraci-doba',
  path: '/oteviraci-doba',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FotogalerieRoute = FotogalerieRouteImport.update({
  id: '/fotogalerie',
  path: '/fotogalerie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fotogalerie': typeof FotogalerieRoute
  '/kontakt': typeof KontaktRoute
  '/menu': typeof MenuRoute
  '/oteviraci-doba': typeof OteviraciDobaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fotogalerie': typeof FotogalerieRoute
  '/kontakt': typeof KontaktRoute
  '/menu': typeof MenuRoute
  '/oteviraci-doba': typeof OteviraciDobaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fotogalerie': typeof FotogalerieRoute
  '/kontakt': typeof KontaktRoute
  '/menu': typeof MenuRoute
  '/oteviraci-doba': typeof OteviraciDobaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fotogalerie' | '/kontakt' | '/menu' | '/oteviraci-doba'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fotogalerie' | '/kontakt' | '/menu' | '/oteviraci-doba'
  id:
    | '__root__'
    | '/'
    | '/fotogalerie'
    | '/kontakt'
    | '/menu'
    | '/oteviraci-doba'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FotogalerieRoute: typeof FotogalerieRoute
  KontaktRoute: typeof KontaktRoute
  MenuRoute: typeof MenuRoute
  OteviraciDobaRoute: typeof OteviraciDobaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oteviraci-doba': {
      id: '/oteviraci-doba'
      path: '/oteviraci-doba'
      fullPath: '/oteviraci-doba'
      preLoaderRoute: typeof OteviraciDobaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotogalerie': {
      id: '/fotogalerie'
      path: '/fotogalerie'
      fullPath: '/fotogalerie'
      preLoaderRoute: typeof FotogalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FotogalerieRoute: FotogalerieRoute,
  KontaktRoute: KontaktRoute,
  MenuRoute: MenuRoute,
  OteviraciDobaRoute: OteviraciDobaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
